export const index = "eggo";

export const imageData = {
  eggo: [
    "desktop-egg.jpg",
    "flower-egg.jpg",
    "float-egg.jpg",
    "albany-egg.jpg",
    "wood-egg.jpg",
    "yuba-egg.jpg",
    "salt-egg.jpg",
    "egg-egg.jpg",
    "rock-egg.jpg",
    "point-egg.jpg",
    "hidden-egg.jpg",
    "egg-bowl.jpg",
  ],
  flight: [
    "birds.jpg",
    "kite.jpg",
    "seagull.jpg",
    "birds-light.jpeg",
    "pigeon.jpg",
  ],
  homo: [
    "clover-bits.jpeg",
    "finch-fern-bits.jpeg",
    "finch-fern-nips.jpeg",
    "grass-side.jpeg",
    "pigeon-fern-bits.jpeg",
    "pigeon-fern-nips.jpeg",
  ],
  garment: [
    "A.jpg",
    "B.jpg",
    "C.jpg",
    "D.jpg",
    "E.jpg",
    "F.jpg",
    "G.jpg",
    "H.jpg",
    "I.jpg",
    "J.jpg",
    "K.jpg",
    "L.jpg",
    "M.jpg",
    "N.jpg",
    "O.jpg",
    "P.jpg",
    "Q.jpg",
    "R.jpg",
    "S.jpg",
    "T.jpg",
    "U.jpg",
    "V.jpg",
    "W.jpg",
    "X.jpg",
    "Y.jpg",
    "Z.jpg",
    "!.jpg",
    "qmark.jpg",
    "dot.jpg",
    "comma.jpg",
  ],
};
