export const lettersData = [
  {
    letter: "A",
    model: "finch",
    photographer: "pigeon",
    location: "hoyt's crossing, ca",
    film: "kodak gold 400",
  },
  {
    letter: "B",
    model: "pigeon + sap",
    photographer: "finch",
    location: "hillside natural area, CA",
    film: "fujicolor superia 400",
  },
  {
    letter: "C",
    model: "pigeon + ducky",
    photographer: "finch",
    location: "wildcat canyon, ca",
    film: "kodak gold 200",
  },
  {
    letter: "comma",
    model: "pigeon",
    photographer: "finch",
    location: "hoyt's crossing, ca",
    film: "kodak gold 400",
  },
  {
    letter: "D",
    model: "pigeon + ducky",
    photographer: "finch",
    location: "wildcat canyon, ca",
    film: "kodak gold 200",
  },
  {
    letter: "E",
    model: "pigeon + ducky",
    photographer: "finch",
    location: "hillside natural area, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "F",
    model: "a",
    photographer: "finch",
    location: "albany bulb, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "G",
    model: "finch + jac",
    photographer: "pigeon",
    location: "sibley preserve, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "H",
    model: "w + finch",
    photographer: "pigeon",
    location: "death valley, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "I",
    model: "pigeon",
    photographer: "finch",
    location: "hoyt's crossing, ca",
    film: "kodak gold 400",
  },
  {
    letter: "J",
    model: "pigeon + ducky",
    photographer: "finch",
    location: "wildcat canyon, ca",
    film: "kodak gold 200",
  },
  {
    letter: "K",
    model: "pigeon",
    photographer: "finch",
    location: "hoyt's crossing, ca",
    film: "kodak gold 200",
  },
  {
    letter: "L",
    model: "pigeon",
    photographer: "finch",
    location: "baker beach, ca",
    film: "kodak gold 400",
  },
  {
    letter: "M",
    model: "a + finch",
    photographer: "pigeon",
    location: "albany bulb, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "N",
    model: "pigeon",
    photographer: "finch",
    location: "echo lake, ca",
    film: "kodak gold 200",
  },
  {
    letter: "O",
    model: "a + finch",
    photographer: "pigeon",
    location: "albany bulb, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "P",
    model: "pigeon",
    photographer: "finch",
    location: "albany bulb, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "Q",
    model: "pigeon + ducky + sap",
    photographer: "finch",
    location: "hillside natural area, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "?",
    model: "pigeon + jac",
    photographer: "finch",
    location: "sibley preserve, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "R",
    model: "pigeon",
    photographer: "finch",
    location: "santa cruz island, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "S",
    model: "pigeon",
    photographer: "finch",
    location: "hoyt's crossing, ca",
    film: "kodak gold 200",
  },
  {
    letter: "T",
    model: "finch",
    photographer: "pigeon",
    location: "death valley, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "U",
    model: "pigeon",
    photographer: "finch",
    location: "hoyt's crossing, ca",
    film: "kodak gold 200",
  },
  {
    letter: "V",
    model: "finch + jac",
    photographer: "pigeon",
    location: "sibley preserve, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "W",
    model: "finch + ducky + sap",
    photographer: "pigeon",
    location: "hillside natural area, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "X",
    model: "pigeon",
    photographer: "finch",
    location: "searles, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "Y",
    model: "pigeon",
    photographer: "finch",
    location: "searles, ca",
    film: "fujicolor superia 400",
  },
  {
    letter: "Z",
    model: "pigeon",
    photographer: "finch",
    location: "death valley, ca",
    film: "fujicolor superia 400",
  },
];
